sudo: required
services:
  - docker

before_install:
  - docker build -t samir2521/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true samir2521/react-test npm test -- --coverage

after_success:
  - docker build -t samir2521/multi-client ./client
  - docker build -t samir2521/multi-nginx  ./nginx
  - docker build -t samir2521/multi-server ./server
  - socker build -t samir2521/multi-worker ./worker

#login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin

#push image to docker
  - docker push samir2521/multi-client
  - docker push samir2521/multi-nginx
  - docker push samir2521/multi-server
  - docker push samir2521/multi-worker
  
  