version: '3'
services:
  postgres:
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: ./Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: ./Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - /c/Users/samir/SamirWork/DockerUdemy/complex/server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - /c/Users/samir/SamirWork/DockerUdemy/complex/client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - /c/Users/samir/SamirWork/DockerUdemy/complex/worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      
